# Generated by Django 3.2 on 2021-06-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DHTDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(default=-1.0)),
                ('humidity', models.FloatField(default=-1.0)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
