# Generated by Django 3.2 on 2021-05-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhtdatamodel',
            name='humidity',
            field=models.FloatField(default=-1.0),
        ),
        migrations.AddField(
            model_name='dhtdatamodel',
            name='temperature',
            field=models.FloatField(default=-1.0),
        ),
    ]
