# Generated by Django 3.2 on 2021-05-25 10:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_app', '0002_auto_20210525_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='dhtdatamodel',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
