# Generated by Django 3.2 on 2021-05-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_handler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicefile',
            name='synthesized',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
